spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitwhere_prod
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
server:
  port: 8082
